#pragma once

#include <array>
#include <cstdint>
#include <iomanip>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>

/*
    Guid.hpp

    Provides a lightweight 128-bit GUID generator for engine resources.  It was
    primarily generated by GPT-5.4 (including this documentation) with a code 
    audit from Claude Sonnet 6.4.

    Overview
    --------
    GopherEngine uses deterministic GUIDs so that the same resource name always
    produces the same GUID across runs and across machines. This is useful for
    asset pipelines, serialization, caching, and cross-referencing resources
    without relying on fragile raw file paths at runtime.

    The GUID generation in this file follows the UUID version 5 pattern:
      1. Start with a fixed namespace UUID.
      2. Normalize the resource name into a canonical string form.
      3. Compute SHA-1(namespace_bytes + normalized_name).
      4. Use the first 16 bytes of the hash as the GUID.
      5. Set the UUID version and variant bits according to RFC 4122.

    Important properties
    --------------------
    - Deterministic:
        The same normalized resource name and namespace always produce the same GUID.
    - Stable:
        GUIDs do not depend on load order, memory addresses, or runtime randomness.
    - Human-debuggable:
        GUIDs can be converted to the standard UUID text form:
        xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    - Namespaced:
        The namespace UUID acts as a domain separator. Changing the namespace
        changes every generated GUID.

    Path normalization
    ------------------
    Resource names are normalized before hashing so that equivalent paths map
    to the same GUID more reliably. The current normalization converts
    backslashes to forward slashes and lowercases ASCII letters. This is
    intended for canonical asset path strings such as:
        assets/meshes/cube.obj
        generated://mesh/cube/w=1/h=1/d=1

    Notes
    -----
    - This is intended for asset/resource identity, not cryptographic security.
    - SHA-1 is used here because UUID v5 is defined in terms of SHA-1.
    - The namespace UUID should be treated as part of the engine's persistent
      asset identity scheme. Do not change it casually after shipping content.
*/

namespace GopherEngine
{
    namespace Detail
    {
        inline std::uint32_t left_rotate(std::uint32_t value, std::uint32_t bits)
        {
            return (value << bits) | (value >> (32 - bits));
        }

        inline std::array<std::uint8_t, 20> sha1(const std::uint8_t* data, std::size_t length)
        {
            std::uint64_t bit_length = static_cast<std::uint64_t>(length) * 8;

            std::vector<std::uint8_t> message(data, data + length);
            message.push_back(0x80);

            while ((message.size() % 64) != 56)
                message.push_back(0x00);

            for (int i = 7; i >= 0; --i)
                message.push_back(static_cast<std::uint8_t>((bit_length >> (i * 8)) & 0xFF));

            std::uint32_t h0 = 0x67452301;
            std::uint32_t h1 = 0xEFCDAB89;
            std::uint32_t h2 = 0x98BADCFE;
            std::uint32_t h3 = 0x10325476;
            std::uint32_t h4 = 0xC3D2E1F0;

            for (std::size_t chunk = 0; chunk < message.size(); chunk += 64)
            {
                std::uint32_t w[80]{};

                for (int i = 0; i < 16; ++i)
                {
                    std::size_t j = chunk + i * 4;
                    w[i] = (static_cast<std::uint32_t>(message[j]) << 24) |
                           (static_cast<std::uint32_t>(message[j + 1]) << 16) |
                           (static_cast<std::uint32_t>(message[j + 2]) << 8) |
                           (static_cast<std::uint32_t>(message[j + 3]));
                }

                for (int i = 16; i < 80; ++i)
                    w[i] = left_rotate(w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16], 1);

                std::uint32_t a = h0;
                std::uint32_t b = h1;
                std::uint32_t c = h2;
                std::uint32_t d = h3;
                std::uint32_t e = h4;

                for (int i = 0; i < 80; ++i)
                {
                    std::uint32_t f = 0;
                    std::uint32_t k = 0;

                    if (i < 20)
                    {
                        f = (b & c) | ((~b) & d);
                        k = 0x5A827999;
                    }
                    else if (i < 40)
                    {
                        f = b ^ c ^ d;
                        k = 0x6ED9EBA1;
                    }
                    else if (i < 60)
                    {
                        f = (b & c) | (b & d) | (c & d);
                        k = 0x8F1BBCDC;
                    }
                    else
                    {
                        f = b ^ c ^ d;
                        k = 0xCA62C1D6;
                    }

                    std::uint32_t temp = left_rotate(a, 5) + f + e + k + w[i];
                    e = d;
                    d = c;
                    c = left_rotate(b, 30);
                    b = a;
                    a = temp;
                }

                h0 += a;
                h1 += b;
                h2 += c;
                h3 += d;
                h4 += e;
            }

            std::array<std::uint8_t, 20> digest{};
            const std::uint32_t h[5] = { h0, h1, h2, h3, h4 };

            for (int i = 0; i < 5; ++i)
            {
                digest[i * 4 + 0] = static_cast<std::uint8_t>((h[i] >> 24) & 0xFF);
                digest[i * 4 + 1] = static_cast<std::uint8_t>((h[i] >> 16) & 0xFF);
                digest[i * 4 + 2] = static_cast<std::uint8_t>((h[i] >> 8) & 0xFF);
                digest[i * 4 + 3] = static_cast<std::uint8_t>(h[i] & 0xFF);
            }

            return digest;
        }

        inline std::uint8_t hex_value(char c)
        {
            if (c >= '0' && c <= '9') return static_cast<std::uint8_t>(c - '0');
            if (c >= 'a' && c <= 'f') return static_cast<std::uint8_t>(10 + c - 'a');
            if (c >= 'A' && c <= 'F') return static_cast<std::uint8_t>(10 + c - 'A');
            throw std::runtime_error("Invalid hex digit in UUID string");
        } 

        inline std::string normalize_resource_name(std::string_view name)
        {
            std::string out;
            out.reserve(name.size());

            for (char c : name)
            {
                if (c == '\\')
                    out.push_back('/');
                else if (c >= 'A' && c <= 'Z')
                    out.push_back(static_cast<char>(c - 'A' + 'a'));
                else
                    out.push_back(c);
            }

            return out;
        }
    }

    struct Guid
    {
        std::array<std::uint8_t, 16> bytes{};

        std::string to_string() const
        {
            std::ostringstream oss;
            oss << std::hex << std::setfill('0');

            for (std::size_t i = 0; i < bytes.size(); ++i)
            {
                oss << std::setw(2) << static_cast<unsigned>(bytes[i]);
                if (i == 3 || i == 5 || i == 7 || i == 9)
                    oss << '-';
            }

            return oss.str();
        }

        bool operator==(const Guid&) const = default;

        static Guid from_string(std::string_view s)
        {
            if (s.size() != 36)
                throw std::runtime_error("UUID string must have length 36");

            if (s[8] != '-' || s[13] != '-' || s[18] != '-' || s[23] != '-')
                throw std::runtime_error("UUID string has invalid dash positions");

            Guid guid;
            std::size_t out = 0;

            for (std::size_t i = 0; i < s.size();)
            {
                if (s[i] == '-')
                {
                    ++i;
                    continue;
                }

                std::uint8_t hi = Detail::hex_value(s[i]);
                std::uint8_t lo = Detail::hex_value(s[i + 1]);
                guid.bytes[out++] = static_cast<std::uint8_t>((hi << 4) | lo);
                i += 2;
            }

            return guid;
        }

        static Guid from_name(std::string_view resource_name,
            std::string_view namespace_uuid = "12345678-1234-5678-1234-567812345678")
        {
            Guid ns = Guid::from_string(namespace_uuid);
            std::string normalized_name = Detail::normalize_resource_name(resource_name);

            std::vector<std::uint8_t> input;
            input.reserve(16 + normalized_name.size());

            input.insert(input.end(), ns.bytes.begin(), ns.bytes.end());
            input.insert(input.end(), normalized_name.begin(), normalized_name.end());

            auto hash = Detail::sha1(input.data(), input.size());

            Guid guid;
            for (std::size_t i = 0; i < 16; ++i)
                guid.bytes[i] = hash[i];

            // UUID version 5
            guid.bytes[6] = static_cast<std::uint8_t>((guid.bytes[6] & 0x0F) | 0x50);

            // RFC 4122 variant
            guid.bytes[8] = static_cast<std::uint8_t>((guid.bytes[8] & 0x3F) | 0x80);

            return guid;
        }
    };

    struct GuidHasher
    {
        std::size_t operator()(const Guid& guid) const noexcept
        {
            std::size_t h = 0;

            for (std::uint8_t b : guid.bytes)
                h = (h * 131) + b;

            return h;
        }
    };
}